version: '3.1'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbit
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456